---
# configure.yaml
#
# Configuration of the system
# This is done using the newly created settings from the setup.yaml
# Split, because setup.yaml needs root login and we disable that as the last step
#
- name: "Configure the system"
  hosts: neo2
  remote_user: pragtich
  vars_files:
    - pr8-vault.yaml
  tasks:
    - name: apt upgrade
      become: yes
      apt:
        update_cache:     yes
        cache_valid_time: 3600
        upgrade:          safe
  
- name: Finalize with sudo rights
  remote_user: pragtich
  hosts: [neo2]

  tasks:
    - name: Get my profile dotfiles
      git:
        repo: 'https://github.com/pragtich/dotfiles.git'
        dest: '~/.dotfiles'
        force: yes
    - name: Install my profile dotfiles
      shell: ~/.dotfiles/install.sh
      args:
        chdir: ~/.dotfiles/
 
