---
# configure.yaml
#
# Configuration of the system
# This is done using the newly created settings from the setup.yaml
# Split, because setup.yaml needs root login and we disable that as the last step
#
- name: "Configure the system"
  hosts: neo2
  remote_user: pragtich
  become: yes

  tasks:
      
    - name: apt upgrade
      apt:
        update_cache:     yes
        cache_valid_time: 3600
        upgrade:          safe
    
      
