---
# configure.yaml
#
# Configuration of the system
# This is done using the newly created settings from the setup.yaml
# Split, because setup.yaml needs root login and we disable that as the last step

### TODO: follow these instructions to the letter and test:
### https://docs.docker.com/engine/install/debian/#install-using-the-repository
# Installs qemu and supporting software and puts home assistant into a virtual server
#
- name: "Configure the system"
  hosts: [neo2, blue]
  remote_user: pragtich
  vars_files:
    - pr8-vault.yaml
  tasks:
    - name: apt upgrade
      become: yes
      apt:
        update_cache:     yes
        cache_valid_time: 3600
        upgrade:          safe

- name: Install QEMU and related software
  hosts: blue
  tasks:
    - name: apt install
      become: yes
      apt:
        name:
          - ipxe-qemu
          - libvirt-daemon
          - qemu-efi-aarch64
          - qemu-efi-arm
          - qemu-system-arm
          - qemu-utils
          - virtinst
            
- name: Create a virtual machine for Homeassistant
          
- name: Finalize with sudo rights
  remote_user: pragtich
  hosts: [neo2, blue]

  tasks:
    - name: Get my profile dotfiles
      git:
        repo: 'https://github.com/pragtich/dotfiles.git'
        dest: '~/.dotfiles'
        force: yes
    - name: Install my profile dotfiles
      shell: ~/.dotfiles/install.sh
      args:
        chdir: ~/.dotfiles/
 
