---
# configure.yaml
#
# Configuration of the system
# This is done using the newly created settings from the setup.yaml
# Split, because setup.yaml needs root login and we disable that as the last step
#
- name: "Configure the system"
  hosts: neo2
  remote_user: pragtich
  become: yes
  
  tasks:
    - name: Add deadsnakes to get newer Python
      apt_repository:
        repo: ppa:deadsnakes/ppa
    - name: apt upgrade
      apt:
        update_cache:     yes
        cache_valid_time: 3600
        upgrade:          safe
  
    - name: Install python 3 and HA requirements
      apt:
        name:
           - python3.7
           - python3.7-venv
           - python3.7-dev
           - python3-pip
           - libffi-dev
           - libssl-dev
        state: present
        
    - name: Install homeassistant user
      user:
        name: homeassistant
        system: yes
        create_home: yes
        password: "*" # Disabled login
        shell: "/bin/bash"
        groups:
          - dialout
        append: yes
    - name: Create virtual environment
      become_user: homeassistant
      become: yes
      pip:
        virtualenv: "~/ha"
        virtualenv_command: pyvenv-3.7
#        virtualenv_python: python3.7
        state: latest
        name:
          - pip
          - setuptools
          #- wheel
          #- homeassistant
    - name: Create virtual environment
      become_user: homeassistant
      become: yes
      pip:
        virtualenv: "~/ha"
        virtualenv_command: pyvenv-3.7
#        virtualenv_python: python3.7
        name:
          #- pip
          - wheel
          - homeassistant
    - name: Create systemd service for homeassistant
      become: yes
      copy:
        src:   home-assistant@homeassistant.service
        dest:  /lib/systemd/system/
    - name: Enable homeassistant service
      systemd:
        name: home-assistant@homeassistant.service
        state: started
        enabled: yes
        daemon_reload: yes
    - name: Get my profile dotfiles
      become_user: pragtich
      git:
        repo: 'https://github.com/pragtich/dotfiles.git'
        dest: '~/.dotfiles'
        force: yes
    - name: Install my profile dotfiles
      become_user: pragtich
      shell: ~/.dotfiles/install.sh
      args:
        chdir: ~/.dotfiles/
    - name: Install homeassistant configuration
      copy:
        src:  "{{ item }}"
        dest: /home/homeassistant/.homeassistant/
      with_fileglob:
        - ha-config/*.yaml

    - name: Get my OLED driver code
      become_user: pragtich
      git:
        repo: 'https://github.com/pragtich/NanoHatOLED.git'
        force: yes
        dest: '~/NanoHatOLED'
    - name: Install my OLED driver
      become: yes
      command: install.sh
      args:
        chdir: '/home/pragtich/NanoHatOLED'
        
# - name: Enable saving to network servers
#   hosts: backup
#   vars:
#     BACKUP_USER:   pragtich
#   tasks:
#   - name: Transfer ssh public ID to backup
#     authorized_key:
#       user: "{{ BACKUP_USER }}"
#       key: "{{ lookup('file', neo2_key.pub }}"

