---
# configure.yaml
#
# Configuration of the system
# This is done using the newly created settings from the setup.yaml
# Split, because setup.yaml needs root login and we disable that as the last step
#
- name: "Configure the system"
  hosts: neo2
  remote_user: pragtich
  vars_files:
    - pr8-vault.yaml
  tasks:
    - name: Add docker key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: Add docker repo
      become: yes
      apt_repository:
        repo: deb  https://download.docker.com/linux/debian buster stable
    - name: apt upgrade
      become: yes
      apt:
        update_cache:     no
        cache_valid_time: 3600
        upgrade:          safe
    - name: install Docker itself
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        - name: Install Home Assistant Supervised required packages
      become: yes
      apt:
        name:
          - avahi-daemon
          - apparmor
          - apparmor-utils
          - python3-apparmor
          - python3-libapparmor
          - python3-pexpect     # Required by ansible expect module
    - name: Put home assistant installer (Manually update now and then!)
      copy:
        src: installer.sh
        dest: installer.sh

    - name: Run the Home Assistant Supervised installer
      # TODO: CREATES toepassen
      become: yes
      expect:
        chdir: ~pragtich/   #TODO variable path or user name
        command: /bin/bash -c "~pragtich/installer.sh"
        responses:
          "[info] Do you want to proceed with that? [N/y]": "y"
        
- name: Finalize with sudo rights
  remote_user: pragtich
  hosts: [neo2]

  tasks:
    - name: Get my profile dotfiles
      git:
        repo: 'https://github.com/pragtich/dotfiles.git'
        dest: '~/.dotfiles'
        force: yes
    - name: Install my profile dotfiles
      shell: ~/.dotfiles/install.sh
      args:
        chdir: ~/.dotfiles/
 
