---
# oled.yaml
#
# Install Nanohat OLED drivers for menu through NanoPi Neo2 metal case's buttons
#

- name: Install OLED 
  remote_user: pragtich
  hosts: [neo2]
  tasks:
    - name: Get my OLED driver code
      # TODO: Clean up the NanoHatOLED structure and make it easier to customize
      # TODO: make this more idempotent (make my own install ?)
      # TODO: remove superuser privileges, only needed because install.sh pulls in Bakebit as root
      become: yes
      git:
        repo: 'https://github.com/pragtich/NanoHatOLED.git'
        force: yes
        dest: '/home/pragtich/NanoHatOLED'
    - name: Install OLED prerequesites
      become: yes
      apt:
        name:
          - python-setuptools
          - python-pip
          - git
          - libi2c-dev
          - python-serial
          - i2c-tools
          - python-smbus
          - minicom
          - python-dev
          - libfreetype6-dev
          - libjpeg-dev
        state: present
    - name: Install python requesites for OLED
      become: yes
      pip:
        executable: /usr/local/bin/pip2.7
        state: latest
        name:
          - Pillow
          - image
        
    - name: Install my OLED driver
      become: yes
      shell: /home/pragtich/NanoHatOLED/install.sh
      args:
        chdir: /home/pragtich/NanoHatOLED/

