---
# oled.yaml
#
# Install Nanohat OLED drivers for menu through NanoPi Neo2 metal case's buttons
#

- name: Install OLED 
  remote_user: pragtich
  hosts: [neo2]
  tasks:
    - name: Get my OLED driver code
      # TODO: Clean up the NanoHatOLED structure and make it easier to customize
      # TODO: make this more idempotent (make my own install ?)
      # TODO: remove superuser privileges, only needed because install.sh pulls in Bakebit as root
      become: yes
      git:
        repo: 'https://github.com/pragtich/NanoHatOLED.git'
        force: yes
        dest: '/home/pragtich/NanoHatOLED'
    - name: Install OLED prerequesites
      become: yes
      apt:
        name:
          - python-setuptools
          - python-pip
          - git
          - libi2c-dev
          - python-serial
          - i2c-tools
          - python-smbus
          - minicom
          - python-dev
          - libfreetype6-dev
          - libjpeg-dev
        state: present
    - name: Install python requirements for OLED
      become: yes
      pip:
        executable: /usr/local/bin/pip2.7
        state: latest
        name:
          - pip
          - image
          - Pillow

    - name: Delete previously present FriendlyArm python requirements for OLED
      # Not nice to do, but necessary because otherwise we get distutils uninstall errors...
      become: yes
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /usr/local/lib/python2.7/dist-packages/RPi/
        - /usr/local/lib/python2.7/dist-packages/RPi.GPIO-0.5.11.egg-info
        - /usr/local/lib/python2.7/dist-packages/psutil/
        - /usr/local/lib/python2.7/dist-packages/_psutil_linux.so
        - /usr/local/lib/python2.7/dist-packages/_psutil_posix.so
        - /usr/local/lib/python2.7/dist-packages/psutil-0.5.0.egg-info/
        - /usr/local/lib/python2.7/dist-packages/psutil-0.5.0-py2.7-linux-aarch64.egg          
    - name: Install FriendlyArm's python requirements for OLED
      become: yes
      pip:
        executable: /usr/local/bin/pip2.7
        state: present
        name:
          - file:///home/pragtich/NanoHatOLED/BakeBit/Script/RPi.GPIO-0.5.11
          - file:///home/pragtich/NanoHatOLED/BakeBit/Script/psutil-0.5.0

    - name: Install FriendlyArm's C requirements (WiringNP) for OLED
      #become: yes
      shell: /home/pragtich/NanoHatOLED/BakeBit/Script/WiringNP/build
      args:
        chdir: /home/pragtich/NanoHatOLED/BakeBit/Script/WiringNP/


    - name: Compile NanoHatOLED script
      become: yes
      shell: gcc Source/daemonize.c Source/main.c -lrt -lpthread -o NanoHatOLED
      args:
        chdir: /home/pragtich/NanoHatOLED
        creates: NanoHatOLED
        
    # - name: Install my OLED driver
    #   become: yes
    #   shell: /home/pragtich/NanoHatOLED/install.sh
    #   args:
    #     chdir: /home/pragtich/NanoHatOLED/

