---
# setup.yaml
#
# Assumes a freshly installed FriendlyArm Ubuntu
# Performs the first time setup which is required for a new system
#

- name: "Do initial stuff with original root account"
  hosts: neo2
  remote_user: root
  vars:
    PR8_ROOT_PWD: '$6$HaRd/fGf3RVZ2RFt$7w3mu0B6gAjNLEqVgqWRwpiCKV/I4LqGoKva5jJ1gj/QVg1oJ.A3XGEYCg.8W1vrTdYFPAU0z41Rr4Y77tqY2/'
    PR8_USER: pragtich
    PR8_USER_PWD: '$6$dq7WwWEFcnLfDKng$DpPNBmBjtl9OApwHwa5hlD97kg3WfaJVXIbUWxadVtYPJZjREBBBcGNxEfNyQZHn0J9KRbD8DENLDUyHyzbiQ/'
    PR8_SHELL: "/bin/bash"
    PR8_KEYS:
      - ~/.ssh/id_rsa.pub
  handlers:
    - name: Restart sshd
      service:
        name:  ssh
        state: restarted
  tasks:
  - name: Set a better pwd for root
    user:
      name:        root
      password:    "{{ PR8_ROOT_PWD }}"
#  - name: Make sure we have a 'wheel' group
#    group:
#      name: wheel
#      state: present
  - name: Add a user for myself
    user:
      name:        "{{ PR8_USER }}"
      password:    "{{ PR8_USER_PWD }}"
      shell:       "{{ PR8_SHELL }}"
      groups:
        - sudo
        - dialout
      append:      yes
  - name: Allow key login for my user
    authorized_key:
      user: "{{ PR8_USER }}"
      key: "{{ lookup('file', item) }}"
    with_items: "{{ PR8_KEYS }}"
  - name: Disable unused accounts
    user:
      name: "{{ item }}"
      password: '*'
    with_items:
      - pi
      - fa
#  - name: Allow 'wheel' group to have passwordless sudo
#    lineinfile:
#      dest: /etc/sudoers
#      state: present
#      regexp: '^%wheel'
#      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#      validate: 'visudo -cf %s'
  - name: Disable password SSH login
    lineinfile:
      dest:   /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line:   "PasswordAuthentication no"
      state:  present
    notify:   Restart sshd
  - name: Disable root loging over SSH
    lineinfile:
      dest:   /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line:   "PermitRootLogin no"
      state:  present
    notify:   Restart sshd
  - name: Set hostname
    hostname:
      name: neo2
