---
# setup.yaml
#
# Assumes a freshly installed FriendlyArm Ubuntu
# Performs the first time setup which is required for a new system
#
# Armbian version
# tested with Armbian 5.75 Bionic Next
#
# TODO: because of the login script, need to do the first login manually
# ssh root@IP  password 1234
# Run through the initial dialogs, then log out
# In the process, make the PR8_USER account and give it a sensible password (matched in the vault)

# TODO: https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

# Usage: 


- name: "Do first configuration. You must run through setup manually first"
  hosts: neo2
  remote_user: root

  vars_files:
    - pr8-vault.yaml
  vars:
    PR8_USER: pragtich
    PR8_SHELL: "/bin/bash"
    PR8_KEYS:
      - ~/.ssh/id_rsa.pub
  handlers:
    - name: Restart sshd
      systemd:
        name:  ssh
        daemon_reload: yes
        state: restarted
  tasks:
  - name: Set a better pwd for root
    user:
      name:        root
      password:    "{{ PR8_ROOT_PWD }}"
#  - name: Make sure we have a 'wheel' group
#    group:
#      name: wheel
#      state: present
  - name: Add a user for myself
    user:
      name:        "{{ PR8_USER }}"
      password:    "{{ PR8_USER_PWD }}"
      shell:       "{{ PR8_SHELL }}"
      generate_ssh_key: yes
      groups:
        - sudo
        - dialout
      append:      yes
  - name: Make a local copy of the private key
    become_user: "{{ PR8_USER }}"
    become: yes
    fetch:
      src: ~/.ssh/id_rsa.pub
      dest: "{{ ansible_hostname }}_key.pub"
  - name: Allow key login for my user
    authorized_key:
      user: "{{ PR8_USER }}"
      key: "{{ lookup('file', item) }}"
    with_items: "{{ PR8_KEYS }}"
  # No unused accounts on armbian
  # - name: Disable unused accounts
  #   user:
  #     name: "{{ item }}"
  #     password: '*'
  #   with_items:
  #     - pi
  #     - fa
  - name: Allow 'sudo' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
  - name: Disable password SSH login
    lineinfile:
      dest:   /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line:   "PasswordAuthentication no"
      state:  present
    notify:   Restart sshd
  - name: Disable root loging over SSH
    lineinfile:
      dest:   /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line:   "PermitRootLogin no"
      state:  present
    notify:   Restart sshd
  - name: Set hostname
    hostname:
      name: neo2

      
