---
# tasks file for pr8-ha
#
# Install Homeassistant onto an armbian target.
#
#

- name: Make sure the apt-get database is up to date
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600    # 1 hour
    
- name: Make sure that we have the Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Make sure that we have Docker's apt repo for buster
  become: yes
  apt_repository:
    repo: deb  https://download.docker.com/linux/debian buster stable

- name: Disable new firewall system and go back to iptables (ansible-galaxy collection install community.general)
  become: yes
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: install Docker and helpers
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Install Home Assistant Supervised required packages
  become: yes
  apt:
    name:
      - avahi-daemon
      - apparmor
      - apparmor-utils
      - python3-apparmor
      - python3-libapparmor
      - python3-pexpect      # Required by expect module in ansible

