---
# tasks file for pr8-ha
#
# Install Homeassistant onto an armbian target.
#
#

- name: Make sure that we have the Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Make sure that we have Docker's apt repo for buster
  become: yes
  apt_repository:
    repo: deb  https://download.docker.com/linux/debian buster stable

- name: Disable new firewall system and go back to iptables (ansible-galaxy collection install community.general)
  become: yes
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Make sure the apt-get database is up to date
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600    # 1 hour
    
- name: install Docker and helpers
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Install Home Assistant Supervised required packages
  become: yes
  apt:
    name:
      - avahi-daemon
      - apparmor
      - apparmor-utils
      - python3-apparmor
      - python3-libapparmor
      - python3-pexpect      # Required by expect module in ansible

- name: Put home assistant installer (Manually update now and then!)
  copy:
    src: installer.sh
    dest: installer.sh
    mode: a+x
- name: Run the Home Assistant Supervised installer
  # TODO: CREATES toepassen
  become: yes
  expect:
    timeout: 120
    chdir: ~pragtich/   #TODO variable path or user name
    command: /bin/bash -c "~pragtich/installer.sh -m raspberrypi4-64"
    responses:
      Do you want to proceed with that?: "y\n"

- name: User must be in docker group
  become: yes
  user:
    name: pragtich #TODO: variabel maken
    groups:
      - docker
      - dialout
    append: yes
